from .llm_node import (
    NODE_CLASS_MAPPINGS as _LLM_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _LLM_NAMES,
)
from .settings_node import (
    NODE_CLASS_MAPPINGS as _SET_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _SET_NAMES,
)
from .chat_node import (
    NODE_CLASS_MAPPINGS as _CHAT_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _CHAT_NAMES,
)

NODE_CLASS_MAPPINGS = {**_LLM_NODES, **_SET_NODES, **_CHAT_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_LLM_NAMES, **_SET_NAMES, **_CHAT_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
