from .batch_node import (
    NODE_CLASS_MAPPINGS as _BATCH_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _BATCH_NAMES,
)
from .list_node import (
    NODE_CLASS_MAPPINGS as _LIST_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _LIST_NAMES,
)

NODE_CLASS_MAPPINGS = {**_BATCH_NODES, **_LIST_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_BATCH_NAMES, **_LIST_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
