from .info_node import (
    NODE_CLASS_MAPPINGS as _INFO_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _INFO_NAMES,
)
from .filter_node import (
    NODE_CLASS_MAPPINGS as _FILTER_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _FILTER_NAMES,
)

NODE_CLASS_MAPPINGS = {**_INFO_NODES, **_FILTER_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_INFO_NAMES, **_FILTER_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
