[project]
name = "kinburg-nodes"
description = "Kinburg's ComfyUI nodes: a local GGUF LLM nodes with on-demand VRAM unloading (+vision). Node for chat with LLM for discuss task before main generation (image or video, etc). An interactive HTML image-comparison node. Other utilities. Accumulator nodes, lora with keywords nodes, save song node and more."
version = "3.0.0"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = []

[project.urls]
Repository = "https://github.com/Kinburg/Kinburg-Nodes"

[tool.comfy]
PublisherId = "kinburg"
DisplayName = "Kinburg-Nodes"
Icon = "https://avatars.githubusercontent.com/u/10453040"
