from .server_node import (
    NODE_CLASS_MAPPINGS as _SRV_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _SRV_NAMES,
)

NODE_CLASS_MAPPINGS = {**_SRV_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_SRV_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
