from .variations_node import (
    NODE_CLASS_MAPPINGS as _PV_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _PV_NAMES,
)

NODE_CLASS_MAPPINGS = {**_PV_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_PV_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
