from .loop_nodes import (
    NODE_CLASS_MAPPINGS as _LOOP_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _LOOP_NAMES,
)

NODE_CLASS_MAPPINGS = {**_LOOP_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_LOOP_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
