from .convert_node import (
    NODE_CLASS_MAPPINGS as _CONV_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _CONV_NAMES,
)
from .diffusion_node import (
    NODE_CLASS_MAPPINGS as _DIFF_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _DIFF_NAMES,
)

NODE_CLASS_MAPPINGS = {**_CONV_NODES, **_DIFF_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_CONV_NAMES, **_DIFF_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
