from .character_card import (
    NODE_CLASS_MAPPINGS as _CC_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _CC_NAMES,
)
from .entity_card import (
    NODE_CLASS_MAPPINGS as _EC_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _EC_NAMES,
)
from .context_collector import (
    NODE_CLASS_MAPPINGS as _CTX_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _CTX_NAMES,
)

NODE_CLASS_MAPPINGS = {**_CC_NODES, **_EC_NODES, **_CTX_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_CC_NAMES, **_EC_NAMES, **_CTX_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
