from .date_node import (
    NODE_CLASS_MAPPINGS as _DATE_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _DATE_NAMES,
)
from .text_concat import (
    NODE_CLASS_MAPPINGS as _TC_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _TC_NAMES,
)
from .color_picker import (
    NODE_CLASS_MAPPINGS as _CP_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _CP_NAMES,
)

NODE_CLASS_MAPPINGS = {**_DATE_NODES, **_TC_NODES, **_CP_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_DATE_NAMES, **_TC_NAMES, **_CP_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
