from .song_node import (
    NODE_CLASS_MAPPINGS as _SS_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _SS_NAMES,
)

NODE_CLASS_MAPPINGS = {**_SS_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_SS_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
