from .collage_node import (
    NODE_CLASS_MAPPINGS as _COLLAGE_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _COLLAGE_NAMES,
)

NODE_CLASS_MAPPINGS = {**_COLLAGE_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_COLLAGE_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
