from .group_control_node import (
    NODE_CLASS_MAPPINGS as _GC_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _GC_NAMES,
)

NODE_CLASS_MAPPINGS = {**_GC_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_GC_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
