from .compare_node import (
    NODE_CLASS_MAPPINGS as _CMP_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _CMP_NAMES,
)
from .color_caption import (
    NODE_CLASS_MAPPINGS as _CC_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _CC_NAMES,
)

NODE_CLASS_MAPPINGS = {**_CMP_NODES, **_CC_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_CMP_NAMES, **_CC_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
