from .lora_nodes import (
    NODE_CLASS_MAPPINGS as _LORA_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _LORA_NAMES,
)

NODE_CLASS_MAPPINGS = {**_LORA_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_LORA_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
