from .set_node import (
    NODE_CLASS_MAPPINGS as _SET_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _SET_NAMES,
)
from .get_node import (
    NODE_CLASS_MAPPINGS as _GET_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _GET_NAMES,
)

NODE_CLASS_MAPPINGS = {**_SET_NODES, **_GET_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_SET_NAMES, **_GET_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
